### ai search
GET http://127.0.0.1:8002/api/search/ai/?q=캐나다

```response example
{
    "content": "캐나다에 대해 무엇을 알고 싶으세요?  더 구체적인 질문을 주시면 더욱 자세하고 도움이 되는 답변을 드릴 수 있습니다.  예를 들어, 다음과 같은 질문을 할 수 있습니다:\n\n* 캐나다의 역사에 대해 알고 싶습니다.\n* 캐나다의 주요 도시는 어디인가요?\n* 캐나다의 기후는 어떤가요?\n* 캐나다의 경제는 어떻습니까?\n* 캐나다 여행에 대한 정보를 얻고 싶습니다.\n* 캐나다의 문화는 어떻습니까?\n* 캐나다의 정치 체제는 어떻습니까?\n\n어떤 정보를 원하시는지 알려주세요!\n"
}
```

### ai search stream
GET http://127.0.0.1:8002/api/search/ai/?q=캐나다&stream=true

```response example
data: {"content": "캐"}

data: {"content": "나다에 대해 무엇을 알고 싶으신가요?  "}

data: {"content": "더 구체적인 질문을 해주시면 더욱 정확한"}

data: {"content": " 정보를 드릴 수 있습니다. 예를 들어, 캐나다의 다음과 같은 정보에 대해 질문하실 수 있습니다:\n\n* **지"}

data: {"content": "리:** 캐나다의 지형, 기후, 주요 도시 등\n* **역사:** 캐나다의 역사적 사건, 원"}

data: {"content": "주민 역사, 식민지 시대 등\n* **문화:** 캐나다의 문화, 언어, 음식, 예술, 축제 등\n* **정치:** 캐나다의 정치 체"}

data: {"content": "제, 정당, 주요 정책 등\n* **경제:** 캐나다의 경제 구조, 주요 산업, 무역 등\n* **사회:** 캐나다의 사회 문제, 인구"}

data: {"content": " 통계, 교육 시스템 등\n* **여행:** 캐나다 여행 정보, 관광 명소, 교통 등\n\n어떤 정보를 원하시는지 알려주세요.\n"}

data: [DONE]
```